alias cbot="cd /wd1/Sorted/Programming/'Counting Bot'"
alias bot="cd /wd1/Sorted/Programming/Botstin"
alias sorted="cd /wd1/Sorted/"
alias pramg="cd /wd1/Sorted/Programming"
alias prgmg="cd /wd1/Sorted/Programming"
alias pypramg="cd /wd1/Sorted/Programming/Python"
alias pyprgmg="cd /wd1/Sorted/Programming/Python"
alias dl="cd ~/Downloads"
alias wxgifcpr="~/Downloads/wxgifcpr.sh"
alias matlab="/wd1/Sorted/MATLAB/R2021b/bin/matlab"
alias plover="~/Plover.AppImage"
alias zulu="date -u +%H:%M"
alias iem="python3 /wd1/Sorted/Programming/iemreader/iemreader.py"

alias short="~/scripts/short"
alias rcomp="killall compton && compton &"
