alias cbot="cd /wd1/Sorted/Programming/'Counting Bot'"
alias bot="cd /wd1/Sorted/Programming/Botstin"
alias sorted="cd /wd1/Sorted/"
alias pramg="cd /wd1/Sorted/Programming"
alias prgmg="cd /wd1/Sorted/Programming"
alias pypramg="cd /wd1/Sorted/Programming/'Python 2021+'"
alias pyprgmg="cd /wd1/Sorted/Programming/'Python 2021+'"
alias dl="cd ~/Downloads"
alias wxgifcpr="~/Downloads/wxgifcpr.sh"
alias matlab="/wd1/Sorted/MATLAB/R2021b/bin/matlab"
alias plover="~/Plover.AppImage"
alias zulu="date -u +%H:%M"

alias short="~/short"
